/*
TWO THINGS TO REMEMBER ABOUT THE DATABASES 
1. ERRORS CAN OCCURE WHILE CONNECTING TO THE DB.
    SOLUTION : ALWAYS USE THE TRY AND CATCH---RAP THE DB CONNECTION IN THIS BLOCKS.
2. ALWAYS REMEMBER THAT THE DATABASE IS STORED IN ANOTHER CONTINENT.
    MEANS : ALWAYS RAP THE DB CONNECTIVITY INSIDE OF THE ASYNC AND AWAIT.
*/
 import connectDB from "./db/index.js";
 import dotenv from 'dotenv';

 dotenv.config({
    path: './env'
 })

 connectDB();